name: Feature Request
description: Suggest an idea for Neo
labels:
  - enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to see added to or changed in Neo, and why?
    validations:
      required: true
